- name: Install Apache httpd from OS repo
  yum: 
    name: httpd
    state: latest
  become: true

- name: Configure apache in EC2 to forward traffic
  shell: /usr/sbin/setsebool -P httpd_can_network_connect 1
  become: true


- name: Add proxypass line in conf file of httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    line: "{{ item }}"
  with_items:
  - 'proxypass /sample http://{{ newip }}:{{ port }}/sample'
  - 'proxypassreverse /sample http://{{ newip }}:{{ port }}/sample'
  become: true
        

- name: enable the httpd service
  service: 
    name: httpd
    enabled: yes
  become: true


- name: start httpd service
  service:
    name: httpd
    state: started
  become: true
