---
- hosts: webservers
  gather_facts: true
  become_method: sudo
  become_user: root
  roles:
    - apache

- hosts: appservers
  gather_facts: true
  become_method: sudo
  become_user: root
  roles:
   - jboss